Run CI tests on watchOS, tvOS, and visionOS
- The watchOS destination can now be used for testing, not just for building.
- Logic for getting device and runtime IDs was updated to handle devices and runtimes where the name is not easily converted to an identifier.
- The visionOS jobs only test on 1.x, because installing the 2.x runtimes via `xcodes` would report success, but the installed runtime would not appear in the available runtimes list.

diff --git a/.github/actions/prepare-simulator/action.yml b/.github/actions/prepare-simulator/action.yml
--- a/.github/actions/prepare-simulator/action.yml
+++ b/.github/actions/prepare-simulator/action.yml
@@ -34,8 +34,15 @@ runs:
       run: |
         RUNTIME="${{ inputs.runtime }}"
         DEVICE="${{ inputs.device }}"
-        DEVICE_ID=com.apple.CoreSimulator.SimDeviceType.$(echo $DEVICE | sed -E -e "s/[ \-]+/ /g" -e "s/[\(\)]//g" -e "s/[^[:alnum:]]/-/g")
-        RUNTIME_ID=com.apple.CoreSimulator.SimRuntime.$(echo $RUNTIME | sed -E -e "s/[ \-]+/ /g" -e "s/[\(\)]//g" -e "s/[^[:alnum:]]/-/g")
+
+        DEVICE_ID=$(xcrun simctl list devicetypes -j | jq -r ".devicetypes.[] | select(.name==\"$DEVICE\").identifier")
+        echo $DEVICE_ID
+        if [ $(echo $DEVICE_ID | wc -l) != 1 ] || [ "$DEVICE_ID" = ""  ]; then echo "Invalid Device ID"; exit 1; fi
+
+        RUNTIME_ID=$(xcrun simctl list runtimes -j | jq -r ".runtimes.[] | select(.name==\"$RUNTIME\").identifier")
+        echo $RUNTIME_ID
+        if [ $(echo $RUNTIME_ID | wc -l) != 1 ] || [ "$RUNTIME_ID" = ""  ]; then echo "Invalid Runtime ID"; exit 1; fi
+
         DESTINATION_ID=$(xcrun simctl create "Custom: $DEVICE, $RUNTIME" $DEVICE_ID $RUNTIME_ID)
         xcrun simctl boot $DESTINATION_ID
         echo "destination-id=$(echo $DESTINATION_ID)" >> $GITHUB_OUTPUT
